name: Reusable workflows

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: The name of the workflow.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Condition and Cancel Workflow
        run: |
          CONDITION=true  # Replace this with your actual condition logic
          if [ "$CONDITION" = true ]; then
            echo "Condition met. Cancelling workflow."
            jobs.cancel()
            exit 0
          fi

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ inputs.name }}
