name: Reusable workflows

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: The name of the workflow.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Exit Workflow from here without running throwing an error
        run: exit 0

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ inputs.name }}
