name: Use Reusable workflows

on:
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Call the reusable workflow
        uses: ./.github/workflows/workflow-1.yml
